baseURL = "http://suixin.monster/"
languageCode = "zh-CN"
title = "隋鑫的个人网站"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false


[Languages]
[languages.zh]
  languageCode = "zh-CN"
  languageName = "简体中文"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:filename/"

[menu]

  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "掘金"
    url = "https://juejin.im/user/5c21e27ee51d452f2c2ef72c"
    weight = 30
  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 100

[params]
    since = 2018
    author = "隋鑫"
    avatar = "/images/me/Running-Man.png"
    subtitle = "欢迎来到隋鑫的个人网站！"
    cdn_url = ""           # Base CDN URL
    home_mode = "my" # posts or other

    google_verification = ""

    description = "隋鑫的个人网站"
    keywords = "隋鑫,前端工程师,2020届本科毕业生"

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "Suizhazha"
    Email   = "573505403@qq.com"
    Wechat = "/images/me/wechat.jpg"